name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    #- name: Install Protoc
    #  uses: arduino/setup-protoc@v1
    #- name: Install Protoc-gen-go
    #  run: go install google.golang.org/protobuf/cmd/protoc-gen-go      
    #- name: Install Protoc-gen-go-grpc
    #  run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc               
    #- name: Generate
    #  run: go generate -v

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
